### ISSUE TITLE
Informative compilation error

### ISSUE THREAD

**Issue by retog** [open-source-labs/vno#133]
Vno tells me that there's a compilation error but no detail wahtsoever:
```
[vno: compiling] => components/Timeline.vue
TypeError: Unable to handle the given specifier: file:///home/reto/Documents/plazi/vnoplay/myfirst/006886959992508213.ts
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async typescriptCompile (https://deno.land/x/vno@v1.4.6/core/lib/ts_compile.ts:21:23)
    at async Module._script (https://deno.land/x/vno@v1.4.6/core/lib/resolver.ts:25:7)
    at async Module.script (https://deno.land/x/vno@v1.4.6/core/lib/parser.ts:39:12)
    at async Component.parseComponent (https://deno.land/x/vno@v1.4.6/core/factory/Component.ts:76:7)
    at async Factory.parseApplication (https://deno.land/x/vno@v1.4.6/core/factory/Factory.ts:117:7)
    at async Factory.build (https://deno.land/x/vno@v1.4.6/core/factory/Factory.ts:147:5)
    at async run (https://deno.land/x/vno@v1.4.6/core/cli/commands.ts:113:3)
    at async main (https://deno.land/x/vno@v1.4.6/install/vno.ts:39:19)
error: Uncaught (in promise) Error: Typescript compilation Error in components/Timeline.vue
    throw new Error(
          ^
    at typescriptCompile (https://deno.land/x/vno@v1.4.6/core/lib/ts_compile.ts:43:11)
    at async Module._script (https://deno.land/x/vno@v1.4.6/core/lib/resolver.ts:25:7)
    at async Module.script (https://deno.land/x/vno@v1.4.6/core/lib/parser.ts:39:12)
    at async Component.parseComponent (https://deno.land/x/vno@v1.4.6/core/factory/Component.ts:76:7)
    at async Factory.parseApplication (https://deno.land/x/vno@v1.4.6/core/factory/Factory.ts:117:7)
    at async Factory.build (https://deno.land/x/vno@v1.4.6/core/factory/Factory.ts:147:5)
    at async run (https://deno.land/x/vno@v1.4.6/core/cli/commands.ts:113:3)
    at async main (https://deno.land/x/vno@v1.4.6/install/vno.ts:39:19)
```
Providing an error message giving more clues about why compilation failed would be very helpful.

**Comment by Ravenstine** [comment]
@retog 

I just happened to stumble upon this... the error coming directly from the Deno runtime when `Deno.emit(...)` is called.  In my project (not Vno but it's doing almost exactly what `core/ts_compile.ts` is doing) it turned out to be related to an imported module that had messed up syntax.  If your files don't show a syntax error then you can individually check imports in the REPL.

You might want to open this issue with Deno since it's throwing an error rather than just including the issue in the diagnostics returned with the compilation result.  Maybe there's a reason for that, but it's both surprising and cryptic.

The best that Vno might be able to do is just catch the error and say that there's an syntax error in an unknown import, but that's vague and presumptive. :shrug:
