### ISSUE TITLE
vno create (w/ defaults) + build fails w/ Deno 1.8.0

### ISSUE THREAD

**Issue by perezd** [open-source-labs/vno#94]
Platform: Windows 10
Deno version: 1.8.0
Vno version: 1.2.1

```
PS G:\src> vno create $proj
️⚠️  Deno requests read access. Grant? [g/d (g = grant, d = deny)] g
️⚠️  Deno requests write access. Grant? [g/d (g = grant, d = deny)] g

Would you like to customize your vno project? (y/n): n

creating your vno project...

PS G:\src> vno build
️⚠️  Deno requests read access. Grant? [g/d (g = grant, d = deny)] g
️⚠️  Deno requests write access. Grant? [g/d (g = grant, d = deny)] g
error: Uncaught (in promise) NotFound: The system cannot find the file specified. (os error 2)
    const json = await Deno.readTextFile(configPath);
                 ^
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpAsync (deno:core/core.js:230:12)
    at async open (deno:runtime/js/30_files.js:45:17)
    at async Object.readTextFile (deno:runtime/js/40_read_file.js:31:18)
    at async configReader (https://deno.land/x/vno@v1.2.1/core/lib/config_reader.ts:15:18)
    at async Factory.init (https://deno.land/x/vno@v1.2.1/core/factory/Factory.ts:75:20)
    at async Factory.createStorage (https://deno.land/x/vno@v1.2.1/core/factory/Factory.ts:91:30)
    at async Factory.build (https://deno.land/x/vno@v1.2.1/core/factory/Factory.ts:127:5)
    at async build (https://deno.land/x/vno@v1.2.1/core/cli/commands.ts:28:3)
    at async https://deno.land/x/vno@v1.2.1/install/vno.ts:19:33
PS G:\src>
```

**Comment by perezd** [comment]
nevermind me, I wasn't in the right directory. Although fwiw a better error message could suffice :)
